### ISSUE TITLE
Could you use more simpler render in live demo?

### ISSUE THREAD

**Issue by MaxGraey** [ycw/Babylon.Font#3]
Currently [live deom](https://ycw.github.io/Babylon.Font/depth1_cache/) uses post-processing (sharping & glow effect) + soft shadows. It's ok for desktop but quite expensive for mobile devices. Also WebGL2.0 not supported on any iOS device (and in Desktop Safari browser). So will be great fallback to WebGL1 in this case.

**Comment by ycw** [comment]
done.

**Comment by MaxGraey** [comment]
Thanks!
